print('=====DESAFIO 2=======')
dia = input('Digite o dia do seu nascimento? ')
mes = input('Digite o mes do seu nascimento? ')
ano = input('Digite o ano do seu nascimento? ')
print('Sua data de nascimento é', dia, "/", mes, "/", ano)
