nome = input('Qual é o seu nome? ')
idade = input('Qual é a sua idade? ')
peso = input('Qual é o seu peso? ')
print('Seu nome é', nome)
print('Sua idade é', idade * 10)
print('Seu peso é', peso)
print('Parabéns, cuide da sua saúde')
